### ISSUE TITLE
JavaScript todo list

### ISSUE THREAD

**Issue by PenguinPaul** [mybb/mybb2#4]
- [x] Modal boxes for login/lost password
- [ ] Modal boxes for report, warn
- [x] Avatar upload with dropzone.js
- [x] Avatar crop? http://acornejo.github.io/jquery-cropbox/
- [ ] Quick reply (needs API)
- [ ] Multiupload
- [x] Multiquote
- [ ] Error notifications for uploads, posts etc (needs API?) (need to decide library?)
- [ ] dropdowns for edit post, etc
- [ ] dropdowns for messages, notifications
- [ ] Usernames should be auticompleted (eg conversations)
- [ ] Poll Ajax voting
- [ ] Like should be Ajax
